//http://localhost:8082/login.jsp?jsessionid=02689a8dbd827fc10c161b4a9be81f7c
drop table if exists member CASCADE;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);